scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
        - gobel-prometheus:9090
  - job_name: 'cadvisor'
    static_configs:
      - targets:
        - gobel-cadvisor:8090
  - job_name: 'node-exporter'
    static_configs:
      - targets:
        - gobel-node-exporter:9100
  - job_name: 'mysqld-exporter'
    static_configs:
      - targets:
        - gobel-mysqld-exporter:9104

